#RAML 1.0
title: To-Do List API

/users
  type: Collection
    get:
        description: Returns all usernames in the tableser
        responses:
          200:
            body:
              application/json

    post:
     description: Adds a user resource to the users table

      body:
        application/json

      responses:
        200:
          body:
            application/json

/users/userID
  {userID}
  type: Collection
      get:
          description: Returns information for a specific user based off userID
            queryParameters:
              userID:
                "Takes in a single ID(Int) and returns the resource for that specific user"
          responses:
            200:
              body:
                application/json

      delete:
        description: Deletes a specific user, based off thier credentials. Will be removed from users table
          responses:
            200:
              body:
                application/json
                  example: {"message:" "User[userID] has been successfully removed"}

/users/userID/lists
  type: Collection
      get:
          description: Returns all lists for the specific userID

          responses:
            200:
              body:
                application/json

      post:
        description: Creates a new list for that users.
         body:
           application/json

         responses:
           200:
             body:
               application/json

      delete:
        description: Deletes a certain list.

          responses:
            200:
              body:
                application/json
                  example: {"message:" "The list has been successfully removed"}

      put:
        description: Will update a users list i.e listname
          responses:
            200:
              body:
                application/json
                  example: {"message:" "The list has been successfully updated"}

/users/userID/lists/listID
  {listID}
  type: Collection
      get:
          description: Returns all lists for the specific userID
             queryParameters:
                listID:
                  "Takes in a single ID(Int) and returns the resource for that specific list"
          responses:
            200:
              body:
                application/json

      post:
        description: Creates a new list item/task in a spoecific list for that users.
         body:
           application/json

         responses:
           200:
             body:
               application/json

      delete:
        description: Deletes a certain list item/task.

          responses:
            200:
              body:
                application/json
                  example: {"message:" "The task has been successfully removed"}

      put:
        description: Will update a users task i.e itemName changed eggs tgo large eggs
          responses:
            200:
              body:
                application/json
                  example: {"message:" "The task has been successfully updated"}






